[CHOBK-202/CHOBK-336] Updated Checkout Pro and Wallet Brick documentations
icaldana/sdk-js pull request #2
Opened 2023-03-06 19:15 UTC by icaldana

## Description
- Updating Checkout Pro documentation to address Bricks on COW changes.
- Updating Wallet Brick documentation to include the changed introduced by Bricks on COW + Bricks on React

## Tip
Use the preview mode to visualize the markdown files

WB --> https://github.com/icaldana/sdk-js/blob/25b54c26e52817f8101c6d272e08547f9b617134/API/bricks/wallet.md
COW: https://github.com/icaldana/sdk-js/blob/25b54c26e52817f8101c6d272e08547f9b617134/API/checkout-pro.md
README --> https://github.com/icaldana/sdk-js/blob/25b54c26e52817f8101c6d272e08547f9b617134/README.md

2023-03-07 11:14 UTC, francineemilia approved these changes

2023-03-07 13:07 UTC, andreagostinho-meli commented on API/checkout-pro.md
> +| `horizontalPadding` | _string_ | Displayed below the checkout button |
Essas descrições ficaram um pouco incompreensíveis para mim, por exemplo, a descrição de `buttonHeight` fala que é exibido abaixo do botão, como assim? Eu interpreto como esse height funcionasse igual a um `margin-bottom`

2023-03-07 13:07 UTC, andreagostinho-meli commented on API/checkout-pro.md
> +Renders the Checkout Button on a given container. This button has the trigger to open the checkout.
```suggestion
Renders the Checkout Button in a given container. This button has the trigger to open the checkout.
```

2023-03-07 13:07 UTC, andreagostinho-meli commented on API/checkout-pro.md
> +Manually unmounts the the opened iframe element. It can be used to generate a new integration instance.
```suggestion
Manually unmounts the opened iframe element. It can be used to generate a new integration instance.
```

2023-03-07 13:07 UTC, andreagostinho-meli commented on README.md
> +| Internet Explorer | 11       |
Nosso brick funciona no Internet Explorer? 🤔 
Acho que não em, porque quando Bricks foi criado lá no início de 2022, tomamos a decisão de não dar suporte ao Internet Explorer.
Precisaria testar hehe.

2023-03-07 13:07 UTC, andreagostinho-meli commented on README.md
> +To install the SDK, you must include script in your application's HTML or install a package on `npm`
```suggestion
To install the SDK, you must include the script in your application's HTML or install a package on `npm`
```

2023-03-07 16:24 UTC, icaldana commented on README.md
> +| Internet Explorer | 11       |
Yep, mas foi um ótimo questionamento. Faz sentido tirar o IE daí se não suportamos em Bricks. Vou alinhar com o Adalton

2023-03-07 17:13 UTC, AleFossati commented on API/checkout-pro.md
> +The alternative values, which are optional, replaces what it defined by default. To check what the alternative values are, plesse check the [Developers site](https://www.mercadopago.com.br/developers
Acho que a frase ficaria um pouco mais clara assim, além de corrigir o "plesse"

```suggestion
The alternative values, which are optional, override the default. To check alternatives values, see the [Developers site](https://www.mercadopago.com.br/developers/pt/docs/checkout-pro/landing)
```

2023-03-07 17:13 UTC, AleFossati commented on API/checkout-pro.md
> +The alternative values, which are optional, replaces what it defined by default. To check what the alternative values are, plesse check the [Developers site](https://www.mercadopago.com.br/developers
Aqui é o mesmo do comentário anterior. Caso ache melhor manter a frase como está, corrigir apenas o "plesse"

2023-03-07 17:13 UTC, AleFossati commented on API/checkout-pro.md
> +| `onSubmit`   | It is called when the user clicks on the button        | **OPTIONAL** |
aqui acho que poderia especificar "clicks the submit button"

2023-03-08 13:01 UTC, AleFossati requested changes

2023-03-08 13:01 UTC, AleFossati commented on API/checkout-pro.md
> +| `initialization` | _object_ | `redirectMode`: _string_ | Customize the opening schema | **OPTIONAL** |
na verdade, olhando a PR do Gui agora, o redirectMode fica dentro de `customization` https://github.com/mercadolibre/fury_op-checkout-bricks/pull/454

2023-03-08 16:48 UTC, icaldana commented on README.md
> +| Internet Explorer | 11       |
Foi decidido deixar por enquanto, porque como você mesmo disse, essa tabela de suporte está relacionada a todos os produtos da SDK e possuímos polyfils para IE.

2023-03-08 16:49 UTC, icaldana commented on API/checkout-pro.md
> +The alternative values, which are optional, replaces what it defined by default. To check what the alternative values are, plesse check the [Developers site](https://www.mercadopago.com.br/developers
Bem melhor, valeu!

2023-03-08 16:57 UTC, icaldana commented on API/checkout-pro.md
> +| `initialization` | _object_ | `redirectMode`: _string_ | Customize the opening schema | **OPTIONAL** |
Estou confirmando isso com ele, valeu!

2023-03-09 12:29 UTC, andreagostinho-meli approved these changes

2023-03-09 12:36 UTC, francineemilia approved these changes

2023-03-09 12:54 UTC, AleFossati commented on API/bricks/wallet.md
> +| `texts.action`             | `string`  | Defines the the call to action text. Options available: `pay`, `buy`. Default is `pay`.                                                        | **OPTIONAL*
```suggestion
| `texts.action`             | `string`  | Defines the call to action text. Options available: `pay`, `buy`. Default is `pay`.                                                        | **OPTIONAL** |
```

2023-03-09 12:54 UTC, AleFossati commented on API/bricks/wallet.md
> +The are three ways to open the checkout experience: redirect on the same tab, which is the default, redirecting to a new tab or using a modal.
```suggestion
There are three ways to open the checkout experience: redirect on the same tab, which is the default, redirecting to a new tab or using a modal.
```

2023-03-09 12:54 UTC, AleFossati commented on API/checkout-pro.md
> +The are three ways to open the checkout experience: redirect on the same tab, which is the default, redirecting to a new tab or using a modal.
```suggestion
There are three ways to open the checkout experience: redirect on the same tab, which is the default, redirecting to a new tab or using a modal.
```

2023-03-09 12:54 UTC, AleFossati commented on API/bricks/wallet.md
> +### The `ErrorCause`'s
O apóstrofo não coloca a palavra no plural

```suggestion
### The `ErrorCause`s
```

2023-03-10 11:18 UTC, AleFossati approved these changes

2023-03-14 12:59 UTC, merged